networks:
  database:
  fastcgi:

services:
  mariadb:
    image: bitnami/mariadb:11.4
    volumes:
      - ./.data/mariadb:/bitnami/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD:-secret}
      - MARIADB_USER=${DB_USER:-app}
      - MARIADB_PASSWORD=${DB_PASSWORD:-secret}
      - MARIADB_DATABASE=${DB_NAME:-app}
    networks:
      - database

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./../app:/opt/app
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf"
      - "./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf"
    depends_on:
      - fpm
    networks:
      - fastcgi

  fpm:
    build:
      context: ../app
      target: fpm
    volumes:
      - ./../app:/opt/app
    depends_on:
      - mariadb
    networks:
      - database
      - fastcgi

  workspace:
    build:
      context: ../app
      target: workspace
    volumes:
      - ./../app:/opt/app
    depends_on:
      - mariadb
    networks:
      - database
